name: Manager
version: '${project.version}'
main: me.cole.managerplugin.Manager
api-version: '1.20'
commands:
  gamemode:
    description: Change gamemode of a player.
  fly:
    description: Toggle a players flight.
