name: Manager
version: '1.0'
main: me.cole.managerplugin.Manager
api-version: '1.20'
commands:
  gamemode:
    aliases: ["gm", "gmod"]
    description: Change gamemode of a player.
  fly:
    description: Toggle a players flight.
  teleport:
    aliases: tp
    description: Teleport to a player.
  setspawn:
    description: Set the spawn location.
  spawn:
    description: Teleport to spawn location.
  time:
    description: Set the time in the players world.
  kick:
    description: Kick a player from the server.
  mute:
    description: Mute a player from typing in chat.
  ban:
    description: Ban a player from the server.
  message:
    aliases: ["msg", "m"]
    description: Send messages between a player.
  reply:
    aliases: ["rep", "r"]
    description: Respond to a message.
  list:
    description: Lists all currently online players.
  give:
    description: Give a specified amount of any item.