name: Manager
version: '1.0'
main: me.cole.managerplugin.Manager
api-version: '1.20'
commands:
  gamemode:
    aliases: ["gm", "gmod"]
    description: Change gamemode of a player.
  fly:
    description: Toggle a players flight.
  teleport:
    aliases: tp
    description: Teleport to a player.
  setspawn:
    description: Set the spawn location.
  spawn:
    description: Teleport to spawn location.
  time:
    description: Set the time in the players world.
  mute:
    description: Mute a player from typing in chat.